[phases.setup]
nixPkgs = ["python311", "gcc", "gfortran", "openblas"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python ml/train_model.py"]

[start]
cmd = "gunicorn run:app -c gunicorn.conf.py"
